# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-21 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseActivityByEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interval_start', models.DateTimeField()),
                ('interval_end', models.DateTimeField(db_index=True)),
                ('activity_type', models.CharField(db_column=b'label', db_index=True, max_length=255)),
                ('count', models.IntegerField()),
                ('education_level', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('interval_end', 'interval_start', 'course_id', 'education_level'),
                'abstract': False,
                'db_table': 'course_activity_education_level',
            },
        ),
        migrations.AlterModelOptions(
            name='courseactivitybygender',
            options={'ordering': ('interval_end', 'interval_start', 'course_id', 'gender')},
        ),
        migrations.AlterModelOptions(
            name='courseactivityweekly',
            options={'get_latest_by': 'interval_end', 'ordering': ('interval_end', 'interval_start', 'course_id')},
        ),
        migrations.AlterModelOptions(
            name='courseenrollmentbybirthyear',
            options={'get_latest_by': 'date', 'ordering': ('date', 'course_id', 'birth_year')},
        ),
        migrations.AlterModelOptions(
            name='courseenrollmentbycountry',
            options={'get_latest_by': 'date', 'ordering': ('date', 'course_id', 'country_code')},
        ),
        migrations.AlterModelOptions(
            name='courseenrollmentbyeducation',
            options={'get_latest_by': 'date', 'ordering': ('date', 'course_id', 'education_level')},
        ),
        migrations.AlterModelOptions(
            name='courseenrollmentbygender',
            options={'get_latest_by': 'date', 'ordering': ('date', 'course_id', 'gender')},
        ),
        migrations.AlterModelOptions(
            name='courseenrollmentdaily',
            options={'get_latest_by': 'date', 'ordering': ('date', 'course_id')},
        ),
        migrations.AlterModelOptions(
            name='courseenrollmentmodedaily',
            options={'get_latest_by': 'date', 'ordering': ('date', 'course_id', 'mode')},
        ),
        migrations.AlterModelOptions(
            name='courseenrollmentmodedailytest',
            options={'get_latest_by': 'date', 'ordering': ('date', 'course_id', 'mode')},
        ),
        migrations.AlterModelOptions(
            name='coursemetasummaryenrollment',
            options={'ordering': ('course_id',)},
        ),
        migrations.AlterModelOptions(
            name='courseprogrammetadata',
            options={'ordering': ('program_id',)},
        ),
        migrations.AlterModelOptions(
            name='gradedistribution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moduleengagement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moduleengagementmetricranges',
            options={},
        ),
        migrations.AlterModelOptions(
            name='problemfirstlastresponseanswerdistribution',
            options={'verbose_name': 'first_last_answer_distribution'},
        ),
        migrations.AlterModelOptions(
            name='problemsandtags',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sequentialopendistribution',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='courseactivitybygender',
            unique_together=set([('course_id', 'interval_end', 'interval_start', 'activity_type', 'gender')]),
        ),
        migrations.AlterUniqueTogether(
            name='courseactivitybyeducation',
            unique_together=set([('course_id', 'interval_end', 'interval_start', 'activity_type', 'education_level')]),
        ),
    ]
