# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-21 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0002_auto_20190621_0545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseactivitybygender',
            unique_together=set([]),
        ),
    ]
